version: 0.{build}
image: Visual Studio 2019
configuration: Release
platform: x64
build:
  verbosity: minimal
after_build:
- cmd: 7z a pcmenc.zip encoder\x64\Release\pcmenc.exe readme.md
artifacts:
- path: '*.zip'